prism_blog_add:
    path:     /Add
    defaults: 
        _controller: PrismBlogBundle:Blog:add

prism_blog_edit:
    path: /Edit/{id}
    defaults: 
        _controller: PrismBlogBundle:Blog:edit
    requirements:
        id: \d+

prism_blog_view:
    path: /Article/{id}
    defaults: 
        _controller: PrismBlogBundle:Blog:view
    requirements:
        id: \d+

