prism_blog:
    resource: "@PrismBlogBundle/Resources/config/routing.yml"
    prefix:   /Blog

prism_esport:
    resource: "@PrismEsportBundle/Resources/config/routing.yml"
    prefix:   /

kms_froala_editor:
    resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
    prefix:   /froalaeditor
